name: "Build Tool Win"
permissions:
  contents: write
  discussions: write
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.8.10'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x86'
      # You can test your matrix by printing the current Python version
      - name: Update pip
        run:  python -m pip install -U --force-reinstall pip
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install Packages
        run: pip install -r requirements.txt
      - name: Pack tool
        run: |
             pyinstaller -Fw tool.py --exclude-module=numpy -i icon.ico --collect-data sv_ttk
             move dist/tool.exe ./
             del *.py
             Remove-Item bin/posix_x86_64 -Recurse
             Remove-Item build -Recurse
             Remove-Item .github -Recurse
             del *.spec
             del *.ico
             del *.bat
             ls
             Compress-Archive -Path ./* -DestinationPath ./MIO-KITCHEN.zip
      - name: Get last commit SHA
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"
      - name: Get last commit message
        id: commit_message
        run: echo "::set-output name=message::$(git log -1 --pretty=%B ${{ steps.get_sha.outputs.sha }})"
      - name: Get Version
        id: tool_version
        run: |
             set ver $(cat bin\setting.ini | findstr version).Split()[2]
             echo $ver
             echo "::set-output name=version::$ver"
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: CI_BUILD
            name: "MIO-KITCHEN-${{ steps.tool_version.outputs.version }}"
            body: |
                 Changelog: ${{ steps.commit_message.outputs.message }}
                 Build times: ${{ github.run_number }}
                 Version: ${{ steps.tool_version.outputs.version }}
                 Author: MIO-KITCHEN-TEAM
            #body_path: CHANGELOG.txt
            draft: false
            prerelease: false
            files: |
              MIO-KITCHEN.zip
