name: "Build Tool"
on:
  push:
    paths:
      - ".github/workflows/main.yml"
  pull_request:
    paths:
      - ".github/workflows/main.yml"
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.8.10'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x86'
      # You can test your matrix by printing the current Python version
      - name: Update pip
        run:  python -m pip install -U --force-reinstall pip
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install Packages
        run: pip install -r requirements.txt
      - name: Pack tool
        run: |
             pyinstaller -Fw tool.py --exclude-module=numpy -i icon.ico --collect-data sv_ttk
             move dist/tool.exe ./
             del *.py
             Remove-Item bin/posix_x86_64 -Recurse
             Compress-Archive -Path ./* -DestinationPath ./MIO-KITCHEN.zip
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            #tag_name: ${{ github.ref }}
            #name: ${{ github.ref }}
            body: TODO New Release.
            #body_path: CHANGELOG.txt
            draft: false
            prerelease: false
            files: |
              MIO-KITCHEN.zip
