name: "Build Tool Win"
permissions:
  contents: write
  discussions: write
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    needs: [build-win,build-linux]
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Get Version
        id: tool_version
        run: |
            set ver $(cat bin\setting.ini | findstr version).Split()[2]
            echo $ver
            echo "::set-output name=version::$ver"
      - name: Get last commit SHA
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"
      - name: Get last commit message
        id: commit_message
        run: echo "::set-output name=message::$(git log -1 --pretty=%B ${{ steps.get_sha.outputs.sha }})"
      - name: Rename Tool
        run: |
          move MIO-KITCHEN-win.zip MIO-KITCHEN-${{ steps.tool_version.outputs.version }}-win.zip
          move MIO-KITCHEN-linux.zip MIO-KITCHEN-${{ steps.tool_version.outputs.version }}-linux.zip
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "CI_BUILD_${{ github.run_number }}"
          name: "MIO-KITCHEN-${{ steps.tool_version.outputs.version }}"
          body: |
            Changelog: ${{ steps.commit_message.outputs.message }}
            Build times: ${{ github.run_number }}
            Version: ${{ steps.tool_version.outputs.version }}
            Author: MIO-KITCHEN-TEAM
            Minimum support: Ubuntu 22.04 (64bit),Windows Vista (32bit)
          #body_path: CHANGELOG.txt
          draft: false
          prerelease: false
          files: |
             "MIO-KITCHEN-${{ steps.tool_version.outputs.version }}-linux.zip"
             "MIO-KITCHEN-${{ steps.tool_version.outputs.version }}-win.zip"

  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.8.10'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x86'
      # You can test your matrix by printing the current Python version
      - name: Update pip
        run:  python -m pip install -U --force-reinstall pip
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install Packages
        run: pip install -r requirements.txt
      - name: Pack tool
        run: |
             pyinstaller -Fw tool.py --exclude-module=numpy -i icon.ico --collect-data sv_ttk --strip
             move dist/tool.exe ./
             del *.py
             Remove-Item bin/posix_x86_64 -Recurse
             Remove-Item build -Recurse
             Remove-Item .github -Recurse
             del *.spec
             del *.ico
             del *.bat
             del *.txt
             del *.md
             ls
             Compress-Archive -Path ./* -DestinationPath ./MIO-KITCHEN-win.zip
      - name: Upload Win Build
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: MIO-KITCHEN-win
          path: 'MIO-KITCHEN-win.zip'
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.8'
          # Optional - x64 or x86 architecture, defaults to x64
      - name: Install Packages
        run: |
            python3 -m pip install -U --force-reinstall pip
            pip3 install -r requirements.txt
            sudo apt update -y && sudo apt install python3-tk zip -y
      - name: Pack Tool
        run: |
             pyinstaller -Fw tool.py --exclude-module=numpy -i icon.ico --collect-data sv_ttk --strip
             mv dist/* ./
             rm -rf *.*
             rm -rf build
             ls
             zip -q -r MIO-KITCHEN-linux.zip ./*
      - name: Upload Linux Build
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: MIO-KITCHEN-linux
          path: 'MIO-KITCHEN-linux.zip'
