name: "Build Tool"
on:
  push:
    paths:
      - ".github/workflows/main.yml"
  pull_request:
    paths:
      - ".github/workflows/main.yml"
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    with: python-version:3.8.10-i386
    steps:
      - uses: actions/checkout@v3
      - name: "Install Python 3.8.10"
